name: Lean CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install elan (Lean toolchain)
        uses: leanprover/elan-action@v1

      - name: Build & test
        run: |
          lake build
          lake test
